Accordion
js-tasks-ru/htmlcss-20230124_aleksey-ruppel pull request #10
Opened 2023-02-01 16:06 UTC by AlexayStar

2023-02-01 16:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-01 21:38 UTC, GSemikozov requested changes

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.page {
1. лишнее
2. нельзя описывать стили одних блоков в других

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.details {
блок называется .accordion )

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
неверно заданы отступы (+ обратить внимание на то что при открытом состоянии отступ снизу меняется)

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
на уровне блока марджины задавать нельзя

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
по структуре - это скорее элемент аккордиона - .accordion__item / .accordion__section , и тогда марджины на уровне элемента задавать можно

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="details" open>
accordion__item

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <div class="page">
переименовать в accordion

2023-02-01 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    line-height: 24px;
не хватает font-family

2023-02-02 09:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-02 09:03 UTC, AlexayStar commented on 03-lection1/02-accordion/accordion.css
> +    line-height: 24px;
добавил R
oboto

2023-02-02 09:03 UTC, AlexayStar commented on 03-lection1/02-accordion/index.html
> +    <div class="page">
переименовал

2023-02-02 09:03 UTC, AlexayStar commented on 03-lection1/02-accordion/index.html
> +        <details class="details" open>
окей

2023-02-02 09:04 UTC, AlexayStar commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
переделал

2023-02-02 09:04 UTC, AlexayStar commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
переделал

2023-02-02 09:05 UTC, AlexayStar commented on 03-lection1/02-accordion/accordion.css
> +.details {
переименовал

2023-02-02 09:05 UTC, AlexayStar commented on 03-lection1/02-accordion/accordion.css
> +.page {
ладно, я просто хотел по центру разместить

2023-02-02 14:55 UTC, GSemikozov approved these changes

2023-02-02 14:55 UTC, merged